steps:
  # 1. Instalar dependências
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # 2. Executar o Build
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # 3. Deploy (O Firebase Tools vai usar a identidade do Cloud Build automaticamente)
  - name: 'node:20'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        npx firebase-tools deploy --only hosting --project $PROJECT_ID --non-interactive

options:
  logging: CLOUD_LOGGING_ONLY